made fixes to multiple areas in front and back end code.
gleekzorp/zac-git-fix-me pull request #1
Opened 2020-11-09 05:16 UTC by zinvergo93

2020-11-09 16:36 UTC, gleekzorp requested changes
Here are a few things to fix up before I can look at this further.

- Please keep all the backend Python code within the `server` folder.
- Please keep all the frontend React code within the `client` folder

2020-11-09 16:36 UTC, gleekzorp commented on .gitignore
> +node_modules
Please add the `.vscode` folder to this as well.  You will also need to stop tracking that file.

Learn more about removing tracking here.  https://stackoverflow.com/questions/24290358/remove-a-folder-from-git-tracking

2020-11-09 23:54 UTC, gleekzorp requested changes
Great job getting those files moved back into the `client` and `server`

- We still have a `package-lock.json`, `package.json`, `pipfile`, and `pipfile.lock` file in our root.
- The only files that should be in our root is the `readme.md`, `.gitignore`, and the two folders `client` and `server`.

Review the following link to learn how to untrack files.  https://stackoverflow.com/questions/24290358/remove-a-folder-from-git-tracking

> You might not have to untrack them, you might need to move them.

2020-11-10 00:08 UTC, zinvergo93 commented
Folder issues resolved

2020-11-10 00:27 UTC, gleekzorp requested changes
Folders are almost ready.

`package-lock.json` and `package.json` should be in the `client` folder.  Those files are for versioning a react or nodejs app.

Once you get those into the correct folder I would really focus your time right now on the python code.  Get the environment setup, the database setup, and the routes working correct with postman.

2020-11-10 05:22 UTC, zinvergo93 commented
Made changes to get all paths running with Postman

2020-11-10 06:01 UTC, gleekzorp requested changes
Awesome!  Keep up the great work.

- Please move the `package.json` into the `client` folder.  The `package.json` is for React and nodeJs version controlling.  Just like the `pipfile` is for Python version controlling.
- Please create a `readme.md` inside the `server` folder so I know how to setup my environment, get my database setup, get my server running, what routes I have available, what data needs to be sent for those routes, etc.
- I would recommend adding the `app.sqlite` file to the `.gitignore` file

2020-11-12 17:25 UTC, gleekzorp requested changes
Looking good.  Here are some extra changes needed before I can test out the `server`.

- I still have a `package.json` inside the `server` folder.  This file needs to live inside the `client` folder.
- The `client` folder has a `Pipfile.lock` file which shouldn't be there.
- I still have an `app.sqlite` file in my `server` folder.  Please look at previous reviews for the link on how to stop tracking.
- `server` `readme` needs information on how to create the `database`.  For instance `from app import db`... etc

Below I have a screenshot of what my folder structure looks like when I pull your current changes.

![move-delete-files](https://user-images.githubusercontent.com/34635302/98973287-cd3c2300-24d0-11eb-8fe6-2714cd95af7c.png)

2020-11-12 17:25 UTC, gleekzorp commented on server/readme.md
> +3. Once successful, you can enter the server by running the file. In your terminal, type "python app.py"
How do I setup my database?

2020-11-12 23:14 UTC, gleekzorp requested changes
Please update the readme with the comment listed below.

2020-11-12 23:14 UTC, gleekzorp commented on server/readme.md
We might want to add a step to install the packages before hopping into the `python` repl.

I got the following error

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gleek/Desktop/development/tests/students/zac-git-fix-me/server/app.py", line 1, in <module>
    from flask import Flask, request, jsonify
ModuleNotFoundError: No module named 'flask'

2020-11-12 23:26 UTC, gleekzorp requested changes

2020-11-12 23:26 UTC, gleekzorp commented on server/readme.md
We only need to use `pipenv install` and that will install all the packages that are listed in the `pipfile`

2020-11-12 23:36 UTC, gleekzorp requested changes
Everything was setup correct.  One minor change in the `server/readme.md` for letting the user know an `app.sqlite` file will be created during step #5.

- Update the `server/readme.md` with a `Routes` section explaining what routes are available.  Such as `GET`, `POST`, etc.  Also maybe let the user know what data needs to be sent during these routes.

> Example:

```
Method: POST
URL: http://localhost:5000/add-book
Content-Type: json
Body: {
    "title": "test 1",
    "author": "test 1",
    "url": "test 1",
    "genre": "test 1",
    "star_rating": "1",
    "book_read": false
}
```

2020-11-13 04:35 UTC, gleekzorp requested changes
Awesome!  I believe the database is all setup now.

Let's start working on getting the client up and going now.

- Please add a `readme.md` in the `client` folder with a description on how I can get the client up and running.
- Your more than welcome to commit any changes required in the client at the same time.

2020-11-24 18:32 UTC, gleekzorp requested changes
Everything seems to be working.  Please update the following.

- Please add a `readme.md` inside your `client` folder with information on how to get the client up and running.
- Getting the following warning:
```
webpackHotDevClient.js:138 src/book.js
  Line 43:23:  Using target="_blank" without rel="noreferrer" is a security risk: see https://html.spec.whatwg.org/multipage/links.html#link-type-noopener  react/jsx-no-target-blank
```
- Getting a `console.log('hi')` from `book.js:22`

2020-11-24 19:02 UTC, gleekzorp approved these changes
Everything is working great.  I'm a little worried about the `pack-lock.json` but we will work on that if it breaks.

2020-11-24 19:02 UTC, merged